### ISSUE TITLE
Generator Costs on Q

### ISSUE THREAD

**Issue by ccoffrin** [aayushGaur/stac#7]
In some cases the matrix mpc.gencost with have two lines for each generator.  If that is the case, the parser should raise a warning "This test case has cost values on reactive power generation that are not displayed by this tool."

See case9Q.m for an example.

**Comment by aayushGaur** [comment]
Added the required warning on the tool-tip for the generators and synchronous condensers.
- For adding a warning in the EW box (Error and Warning box at the bottom of the page) we need to attach the DOM ID of an element with the warning so that the user can zoom in on an element when he/she click on that warning - Please advise how should this be handled as the warning message in this case is common for all top decorators?

**Comment by ccoffrin** [comment]
Because the Q values are omitted from every generator, adding a warning on each one is a bit redundant. 

I think it is simpler just to raise a dialog box when the cases is loaded warning the user that some information is not displayed.  The rest of the tool can remain the same.

**Comment by aayushGaur** [comment]
Updated to display the following message to the user:
'Warning: this test case has cost values on reactive power generation that are not displayed by this tool.'
